### ISSUE TITLE
v0.59.0 compiled binary: all provider modules fail to load (Cannot find module './anthropic.js')

### ISSUE THREAD

**Issue by saemanas** [badlogic/pi-mono#2314]
After updating to v0.59.0, the compiled binary crashes on the first message:

```
Error: ResolveMessage: Cannot find module './anthropic.js' from '/$bunfs/root/pi'
```

**Root cause:** The lazy-loading refactor in #2297 introduced a `dynamicImport` wrapper that routes all provider specifiers through a function parameter. Bun's `bun build --compile` uses static AST analysis to decide what goes into the binary's virtual filesystem -- once the specifier is passed through a function variable, Bun can't trace it and excludes the module entirely.

```ts
// register-builtins.ts
const dynamicImport: DynamicImport = (specifier) => import(specifier);

// Bun cannot trace what `specifier` will be -- module not bundled
dynamicImport(ANTHROPIC_PROVIDER_SPECIFIER)
```

All 9 non-Bedrock providers are affected. Bedrock already used `"./amazon-" + "bedrock.js"` (string concatenation) to intentionally stay out of the bundle, so that one is unchanged.

**Fix:** Replace `dynamicImport(SPECIFIER)` with inline `import("./provider.js")` for each load function. Bun can statically analyze string literals in function bodies -- lazy-loading behavior is preserved, modules just get bundled correctly.

I have a fix ready on a fork if this gets the go-ahead.

Related Bun issues: oven-sh/bun#11732, oven-sh/bun#6893

**Comment by badlogic** [comment]
fixed in main.
