### ISSUE TITLE
Standalone coding-agent v0.60.0 fails to load Amazon Bedrock provider

### ISSUE THREAD

**Issue by unexge** [badlogic/pi-mono#2349]
### What happened?

I'm using standalone [Linux binary](https://github.com/badlogic/pi-mono/releases/download/v0.60.0/pi-linux-x64.tar.gz) with Amazon Bedrock provider, and with v0.60.0 it fails via:
```
 Error: ResolveMessage: Cannot find module './amazon-bedrock.js' from '/$bunfs/root/pi'
```

It was working on v0.59.0

### Steps to reproduce

```bash
$ cd /tmp
$ wget https://github.com/badlogic/pi-mono/releases/download/v0.60.0/pi-linux-x64.tar.gz
$ tar -xzf pi-linux-x64.tar.gz
$ AWS_PROFILE=test ./pi/pi --provider amazon-bedrock hello
...
Error: ResolveMessage: Cannot find module './amazon-bedrock.js' from '/$bunfs/root/pi'
```

### Expected behavior

Expected standalone coding-agent to correctly bundle Amazon Bedrock provider

### Version

0.60.0

**Comment by unexge** [comment]
I asked my clanker and it suggested replacing `importNodeOnlyProvider` with direct `import` here:
https://github.com/badlogic/pi-mono/blob/8a8e2a8049fba194d999cf7f3ec4b247910657ee/packages/ai/src/providers/register-builtins.ts#L335

It seemed to fix the problem on my local, but I assume there was a reason to do that in the first place and there is also seems to a script to register Bedrock provider for Bun binary: https://github.com/badlogic/pi-mono/blob/main/packages/coding-agent/src/bun/register-bedrock.ts. I'll talk with my clanker to see if I can figure out what's wrong with that
