### ISSUE TITLE
Cannot find module '@mariozechner/pi-tui' After updating to 0.56.0

### ISSUE THREAD

**Issue by it-ony** [badlogic/pi-mono#1820]
### What happened?

  npm:@tmustier/pi-usage-extension (user) index.ts
    Failed to load extension: Cannot find module '@mariozechner/pi-tui'
Require stack:
- /Users/Tony.Findeisen/.nvm/versions/node/v22.19.0/lib/node_modules/@tmustier/pi-usage-extension/index.ts

### Steps to reproduce

* npm install -g @mariozechner/pi-coding-agent@0.56.0
* pi

**Comment by ADIX7** [comment]
Same for the npm:pi-subagents extension

**Comment by jeroendee** [comment]
Yup same here. 

When loading an extension that has a dependency on `pi-tui` this will yield: `Failed to load extension: Cannot find module '@mariozechner/pi-tui'`

~Asking clanker as we speak.~ 

@ilyapoz beat me to it.

**Comment by ilyapoz** [comment]
[generated by PI/claude-opus]:
**Root cause identified.** This is a regression in the jiti alias setup in `loader.js`.

In **0.55.4**, the extension loader resolved aliases to real file paths using `require.resolve()`:

```js
// 0.55.4 - loader.js getAliases()
_aliases = {
    "@mariozechner/pi-coding-agent": packageIndex,
    "@mariozechner/pi-agent-core": require.resolve("@mariozechner/pi-agent-core"),
    "@mariozechner/pi-tui": require.resolve("@mariozechner/pi-tui"),
    "@mariozechner/pi-ai": require.resolve("@mariozechner/pi-ai"),
    "@sinclair/typebox": typeboxRoot,
};
```

In **0.56.0**, this was changed to `resolveWorkspaceOrSpecifier()` which first checks for workspace source paths (`packages/ai/src/index.ts`, etc.) and falls back to the bare specifier string:

```js
// 0.56.0 - loader.js getAliases()
const resolveWorkspaceOrSpecifier = (workspaceRelativePath, specifier) => {
    const workspacePath = path.join(packagesRoot, workspaceRelativePath);
    if (fs.existsSync(workspacePath)) {
        return workspacePath;  // Only works in pi-mono dev workspace
    }
    return specifier;  // Bare specifier, e.g. "@mariozechner/pi-ai" — broken fallback
};
```

For anyone developing inside the `pi-mono` monorepo, the workspace paths exist and aliases resolve correctly. For everyone else (npm global install, npm package extensions), the fallback returns the bare specifier string (e.g. `"@mariozechner/pi-ai"`), which jiti then tries to resolve from the **extension's** directory — where the package isn't installed.

Additionally, `require.resolve("@mariozechner/pi-ai")` also fails in 0.56.0 because `pi-ai`'s `package.json` now uses ESM-only exports (`"import"` condition only, no `"main"` or `"require"`). So the fix can't simply revert to the old `require.resolve()` calls — it needs to handle the ESM-only exports.

**Suggested fix:** resolve the alias paths using `import.meta.resolve()` (available since Node 20) or use `createRequire(import.meta.url)` with the `exports` conditions, falling back to manual path construction using `path.resolve(__dirname, ...)` relative to the loader's location in the installed package.

**Workaround:** Downgrade to 0.55.4:
```
npm install -g @mariozechner/pi-coding-agent@0.55.4
```

**Affects:** All extensions importing `@mariozechner/pi-ai`, `@mariozechner/pi-tui`, or `@mariozechner/pi-agent-core` when pi is installed via npm (i.e. not running from the pi-mono workspace).

**Comment by ilyapoz** [comment]
> @ilyapoz beat me to it.

I asked it to find the issue and it suggested that the description is too thin and posted the comment itself :D Wow, what times we live in :D

<img width="2294" height="279" alt="Image" src="https://github.com/user-attachments/assets/137807e3-29cf-49bf-8f5a-00afdafc0275" />

**Comment by NickyTesla** [comment]
Having related issue since upgrading - Pi resolved itself for now but it'll break next update:


Extension loading broken in 0.56.0 (Node.js/npm install): Cannot find module '@mariozechner/pi-ai'

When pi-coding-agent is installed globally via npm, pi-ai and pi-tui get nested inside pi-coding-agent/node_modules/ rather than hoisted. The getAliases() function in loader.ts falls back to bare specifiers when the monorepo workspace paths (ai/src/index.ts, tui/src/index.ts) don't exist, which makes the aliases no-ops. Extensions then can't resolve these imports.

The fix in getAliases() should resolve to the actual installed paths when workspace paths are missing, e.g.:  

```js
const resolveWorkspaceOrSpecifier = (workspaceRelativePath, specifier) => {
    const workspacePath = path.join(packagesRoot, workspaceRelativePath);
    if (fs.existsSync(workspacePath)) return workspacePath;

// Fall back to resolving from this package's node_modules
    try { 
        return require.resolve(specifier); 
    } catch { 
        return specifier; 
    }
};
```
