### ISSUE TITLE
Bug: openai-responses provider fails to load in v0.66.0 - module resolution error

### ISSUE THREAD

**Issue by valtterimelkko** [badlogic/pi-mono#2966]
## Bug Description
After upgrading `@mariozechner/pi-coding-agent` from v0.65.0 to v0.66.0, the `openai-responses` provider fails to load with a module resolution error when using GitHub Copilot models (e.g., `gpt-5.4`).

## Error Message
```
Cannot find module '/root/pi-web-ui/server/node_modules/@mariozechner/pi-ai/dist/providers/openai-responses.js' 
imported from /root/pi-web-ui/server/node_modules/@mariozechner/pi-ai/dist/providers/register-builtins.js
```

## Steps to Reproduce
1. Upgrade to `@mariozechner/pi-coding-agent@0.66.0`
2. Create a new session with a GitHub Copilot model (e.g., `github-copilot/gpt-5.4`)
3. Send any message
4. The assistant responds with an error instead of generating content

## Session File Output
```json
{
  "type": "message",
  "message": {
    "role": "assistant",
    "stopReason": "error",
    "errorMessage": "Cannot find module '/root/pi-web-ui/server/node_modules/@mariozechner/pi-ai/dist/providers/openai-responses.js' imported from /root/pi-web-ui/server/node_modules/@mariozechner/pi-ai/dist/providers/register-builtins.js"
  }
}
```

## Environment
- **OS**: Ubuntu 22.04 (Docker container)
- **Node.js**: v24.14.0
- **Package**: `@mariozechner/pi-coding-agent@0.66.0`
- **Dependency**: `@mariozechner/pi-ai@0.66.0`

## Project Structure
The project is an npm workspace monorepo:
```
pi-web-ui/
├── node_modules/@mariozechner/pi-ai/  (actual location)
├── server/
│   └── node_modules/ (empty @mariozechner/ - uses hoisted deps)
├── client/
└── package.json (workspaces: ["server", "client", "shared"])
```

## Root Cause Analysis
The error path in the error message is incorrect:
- **Error says**: `/root/pi-web-ui/server/node_modules/@mariozechner/pi-ai/dist/providers/openai-responses.js`
- **Actual file**: `/root/pi-web-ui/node_modules/@mariozechner/pi-ai/dist/providers/openai-responses.js`

The `register-builtins.js` file uses a relative import:
```javascript
openAIResponsesProviderModulePromise ||= import("./openai-responses.js")
```

However, the module resolution seems to be resolving relative to a non-existent path. This suggests either:
1. An ESM module resolution change in v0.66.0
2. A bundling/packaging issue where the relative imports aren't resolving correctly
3. A change in how `pi-ai` exports its providers

## Workaround
Downgrading to `@mariozechner/pi-coding-agent@0.65.0` resolves the issue.

## Additional Notes
- The `pi-ai` package.json exports field includes: `"./openai-responses": { "import": "./dist/providers/openai-responses.js" }`
- Other providers (anthropic, google, etc.) may also be affected but were not tested
- This affects the `openai-responses` API which is used by GitHub Copilot models
